name: Build IPA (P-Slice)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Haxe
        run: |
          brew update
          brew install haxe

      - name: Setup Haxelib
        run: |
          haxelib setup ~/haxelib

      - name: Install EXACT dependencies
        run: |
          haxelib install hxcpp 4.3.2
          haxelib install lime 8.2.2
          haxelib install openfl 9.3.3
          haxelib install flixel 5.6.2
          haxelib install flixel-addons 3.3.2
          haxelib install hscript
          haxelib install tjson
          haxelib install flxanimate
          haxelib install hxvlc

      - name: Set global versions
        run: |
          haxelib set lime 8.2.2
          haxelib set openfl 9.3.3
          haxelib set flixel 5.6.2

      - name: Show versions
        run: |
          haxe -version
          haxelib list

      - name: Build iOS (no signing)
        run: |
          xcodebuild \
            -project PSliceEngine.xcodeproj \
            -scheme PSliceEngine \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            clean build
